name: Deploy API production

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest

    steps:
      - name: Deploy na VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            set -e

            cd ~/projects/financy/backend

            echo "Atualizando código..."
            git pull origin main

            echo "Construindo imagem..."
            docker compose -f traefik.yml build

            echo "Subindo API..."
            docker compose -f traefik.yml up -d

            echo "Executando migrations..."
            docker compose -f traefik.yml exec -T api npx prisma migrate deploy

            echo "Limpando imagens antigas..."
            docker image prune -f

            echo "Deploy concluído!"
